import React from 'react';

export const ImpactGovernance: React.FC = () => {
  return (
    <section id="governance" className="py-14 sm:py-20 px-4 sm:px-8 border-b border-[#ddc0b8]/60 bg-white">
      <div className="max-w-7xl mx-auto space-y-12">
        <div className="max-w-3xl space-y-3">
          <div className="text-[12px] uppercase tracking-wider text-[#9d3d1e] font-bold">
            Public Systems Architecture
          </div>
          <h2 className="text-2xl sm:text-4xl font-bold font-serif-headline text-[#201a18] text-balance">
            Governance-grade auditability engineered for state-level scale.
          </h2>
          <p className="text-[16px] text-[#56423c] leading-relaxed">
            Deploying technology to 5,000+ public schools demands auditability, institutional accountability, and device frugality. VIDYA VANI was designed directly in partnership with the operational guidelines of the Jharkhand Education Project Council (JEPC).
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-stretch">
          {/* Data Governance Box */}
          <div className="p-6 sm:p-8 rounded-2xl bg-[#fdf1ed] border-2 border-[#ddc0b8] shadow-xs flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-[#9d3d1e] text-white flex items-center justify-center">
                  <span className="material-symbols-outlined text-2xl">policy</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold font-serif-headline text-[#201a18]">
                    Auditable Linguistic Pipeline
                  </h3>
                  <p className="text-[12px] text-[#56423c]">Strict separation of verified vs novel content</p>
                </div>
              </div>

              <div className="space-y-3 text-[14px] text-[#56423c] leading-relaxed">
                <p>
                  In a primary classroom, incorrect dialectal instruction or erroneous translation can entrench misconception. VIDYA VANI protects pedagogical integrity through three audit tiers:
                </p>

                <div className="p-3.5 bg-white rounded-xl border border-[#ddc0b8] space-y-1">
                  <div className="flex items-center gap-2 font-bold text-[#3a6848] text-[13px]">
                    <span className="material-symbols-outlined text-base">check_circle</span>
                    <span>Tier 1: Verified Local Match</span>
                  </div>
                  <p className="text-[12px]">
                    Instructional sentences vetted by CIIL &amp; JEPC master teachers, stamped into the on-device SQLite database.
                  </p>
                </div>

                <div className="p-3.5 bg-white rounded-xl border border-[#ddc0b8] space-y-1">
                  <div className="flex items-center gap-2 font-bold text-[#8d4b00] text-[13px]">
                    <span className="material-symbols-outlined text-base">schedule</span>
                    <span>Tier 2: Machine Translated — Pending Review</span>
                  </div>
                  <p className="text-[12px]">
                    Genuinely novel sentences generated by NLLB-200 are visually tagged so the teacher knows it is an intelligent fallback awaiting linguistic audit.
                  </p>
                </div>

                <div className="p-3.5 bg-white rounded-xl border border-[#ddc0b8] space-y-1">
                  <div className="flex items-center gap-2 font-bold text-[#9d3d1e] text-[13px]">
                    <span className="material-symbols-outlined text-base">sync</span>
                    <span>Tier 3: Teacher Correction Queue</span>
                  </div>
                  <p className="text-[12px]">
                    Teachers can tap "Suggest Correction" or record audio nuance offline; corrections queue locally and sync at the Block Resource Centre (BRC).
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Hardware & Systems Specifications */}
          <div className="p-6 sm:p-8 rounded-2xl bg-white border-2 border-[#ddc0b8] shadow-xs flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-[#3a6848] text-white flex items-center justify-center">
                  <span className="material-symbols-outlined text-2xl">memory</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold font-serif-headline text-[#201a18]">
                    Frugal Hardware Profile
                  </h3>
                  <p className="text-[12px] text-[#56423c]">Engineered for budget government tablet tenders</p>
                </div>
              </div>

              <div className="space-y-3.5 text-[14px] text-[#56423c]">
                <div className="flex items-center justify-between p-3 rounded-xl bg-[#f7ebe8] border border-[#ddc0b8]">
                  <span className="font-bold text-[#201a18]">Minimum Target Device</span>
                  <span className="font-mono text-[13px] text-[#9d3d1e] font-bold">2GB RAM / 16GB Storage</span>
                </div>

                <div className="flex items-center justify-between p-3 rounded-xl bg-[#f7ebe8] border border-[#ddc0b8]">
                  <span className="font-bold text-[#201a18]">Operating System</span>
                  <span className="font-mono text-[13px] text-[#9d3d1e] font-bold">Android 9.0+ (Pie)</span>
                </div>

                <div className="flex items-center justify-between p-3 rounded-xl bg-[#f7ebe8] border border-[#ddc0b8]">
                  <span className="font-bold text-[#201a18]">Total Offline Footprint</span>
                  <span className="font-mono text-[13px] text-[#3a6848] font-bold">384 MB (1.2% of 32GB)</span>
                </div>

                <div className="flex items-center justify-between p-3 rounded-xl bg-[#f7ebe8] border border-[#ddc0b8]">
                  <span className="font-bold text-[#201a18]">Local Storage Encryption</span>
                  <span className="font-mono text-[13px] text-[#201a18] font-bold">Salted SQLiteCipher</span>
                </div>

                <div className="flex items-center justify-between p-3 rounded-xl bg-[#f7ebe8] border border-[#ddc0b8]">
                  <span className="font-bold text-[#201a18]">Display Compatibility</span>
                  <span className="font-mono text-[13px] text-[#201a18] font-bold">7" Tablet &amp; 1080p TV Cast</span>
                </div>
              </div>

              <p className="text-[13px] text-[#56423c] italic border-t border-[#ddc0b8] pt-3">
                "No school is priced out. No student is left waiting for a cell tower that will not arrive."
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
